#if !canImport(ObjectiveC)
import XCTest

extension DurationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DurationTests = [
        ("testComparableReduced", testComparableReduced),
        ("testInitOperator", testInitOperator),
        ("testRange", testRange),
    ]
}

extension DurationTreeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DurationTreeTests = [
        ("testInitDuration", testInitDuration),
        ("testInitDurationProportionTreeOperator", testInitDurationProportionTreeOperator),
        ("testInitEmptyArray", testInitEmptyArray),
        ("testInitSubdivisionAndProportionTree", testInitSubdivisionAndProportionTree),
        ("testInitSubdivisionOperator", testInitSubdivisionOperator),
        ("testInitWithRelativeDurations", testInitWithRelativeDurations),
        ("testInitWithRelativeDurations13Over12", testInitWithRelativeDurations13Over12),
        ("testInitWithRelativeDurations4Over5", testInitWithRelativeDurations4Over5),
        ("testInitWithRelativeDurations5Over4", testInitWithRelativeDurations5Over4),
        ("testLeafOffsets", testLeafOffsets),
        ("testManyDurationTrees", testManyDurationTrees),
        ("testMultipleLeaves", testMultipleLeaves),
        ("testSingleLeaf", testSingleLeaf),
    ]
}

extension EasingEvaluateTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EasingEvaluateTests = [
        ("testLinear", testLinear),
        ("testPowerInHalf", testPowerInHalf),
        ("testPowerInOne", testPowerInOne),
        ("testPowerInOutOne", testPowerInOutOne),
        ("testPowerInOutThree", testPowerInOutThree),
        ("testPowerInOutTwo", testPowerInOutTwo),
        ("testPowerInTwo", testPowerInTwo),
        ("testSineInOut", testSineInOut),
    ]
}

extension EasingIntegrateTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EasingIntegrateTests = [
        ("testLinear", testLinear),
        ("testPowerInHalf", testPowerInHalf),
        ("testPowerInOne", testPowerInOne),
        ("testPowerInOutOne", testPowerInOutOne),
        ("testPowerInOutThree", testPowerInOutThree),
        ("testPowerInOutTwo", testPowerInOutTwo),
        ("testPowerInTwo", testPowerInTwo),
        ("testSineInOut", testSineInOut),
    ]
}

extension MeterCollectionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MeterCollectionTests = [
        ("testFragmentOutOfRange", testFragmentOutOfRange),
        ("testFragmentRangeWithinSingleMeter", testFragmentRangeWithinSingleMeter),
        ("testFragmentUpperBoundBeyondEnd", testFragmentUpperBoundBeyondEnd),
        ("testFuzzManyFragments", testFuzzManyFragments),
        ("testTruncatingFragment", testTruncatingFragment),
    ]
}

extension MeterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MeterTests = [
        ("testAdditiveMeter", testAdditiveMeter),
        ("testBeatOffsets", testBeatOffsets),
        ("testBeatOffsetsAdditive", testBeatOffsetsAdditive),
        ("testBeatOffsetsFractional", testBeatOffsetsFractional),
        ("testFractionalMeter", testFractionalMeter),
        ("testIrrationalMeter", testIrrationalMeter),
        ("testManyMetersSum", testManyMetersSum),
        ("testMetersSum", testMetersSum),
        ("testNormalMeter", testNormalMeter),
    ]
}

extension ProportionTreeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ProportionTreeTests = [
        ("testInit", testInit),
        ("testmatchingParentsToChildrenSingleDepthDownThree", testmatchingParentsToChildrenSingleDepthDownThree),
        ("testmatchingParentsToChildrenSingleDepthDownTwo", testmatchingParentsToChildrenSingleDepthDownTwo),
        ("testmatchingParentsToChildrenSingleDepthUp", testmatchingParentsToChildrenSingleDepthUp),
        ("testMatchParentsVeryNestedMultipleCases", testMatchParentsVeryNestedMultipleCases),
        ("testNormalizedNested", testNormalizedNested),
        ("testNormalizeSingleDepth", testNormalizeSingleDepth),
        ("testNormalizeSingleDepthBranchOfSingleLeafOf3", testNormalizeSingleDepthBranchOfSingleLeafOf3),
        ("testNormalizeVeryNested", testNormalizeVeryNested),
        ("testReducedNested", testReducedNested),
        ("testReducedSingleDepth", testReducedSingleDepth),
        ("testReducedVeryNested", testReducedVeryNested),
        ("testScaleSimple", testScaleSimple),
    ]
}

extension RhythmTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RhythmTests = [
        ("testDuratedEvents", testDuratedEvents),
        ("testInitWithDurationAndContextsUsage", testInitWithDurationAndContextsUsage),
        ("testInitWithDurationAndContextTupleUsage", testInitWithDurationAndContextTupleUsage),
        ("testInitWithDurationAndValueTupleUsage", testInitWithDurationAndValueTupleUsage),
        ("testLengths", testLengths),
        ("testLengthsAllTies", testLengthsAllTies),
        ("testLengthsSingleAllTies", testLengthsSingleAllTies),
        ("testLengthsSingleTiesAndEvents", testLengthsSingleTiesAndEvents),
        ("testLengthsSingleTiesEventsAndRests", testLengthsSingleTiesEventsAndRests),
        ("testLengthsTiesAndEvents", testLengthsTiesAndEvents),
        ("testLengthsTiesEventsAndRests", testLengthsTiesEventsAndRests),
        ("testMapEvents", testMapEvents),
        ("testReplaceEvents", testReplaceEvents),
    ]
}

extension RhythmTreeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RhythmTreeTests = [
        ("testInit", testInit),
    ]
}

extension TempoInterpolationCollectionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TempoInterpolationCollectionTests = [
        ("testBuilderSingleInterpolation", testBuilderSingleInterpolation),
        ("testBuilderSingleStatic", testBuilderSingleStatic),
        ("testFirstOffset", testFirstOffset),
        ("testFragment", testFragment),
        ("testMoreComplexFragment", testMoreComplexFragment),
        ("testSimpleFragment", testSimpleFragment),
    ]
}

extension TempoInterpolationFragmentTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TempoInterpolationFragmentTests = [
        ("testSecondsOffsetStatic120BPMFirstBeats", testSecondsOffsetStatic120BPMFirstBeats),
        ("testSecondsOffsetStatic120BPMLastBeats", testSecondsOffsetStatic120BPMLastBeats),
        ("testSecondsOffsetStatic120BPMMiddleBeats", testSecondsOffsetStatic120BPMMiddleBeats),
    ]
}

extension TempoInterpolationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TempoInterpolationTests = [
        ("testDurationStatic120BPM", testDurationStatic120BPM),
        ("testDurationStatic30BPM", testDurationStatic30BPM),
        ("testDurationStatic60BPM", testDurationStatic60BPM),
        ("testSecondsOffsetLinear_120to120", testSecondsOffsetLinear_120to120),
        ("testSecondsOffsetLinear_120to60_wholeNoteDuration", testSecondsOffsetLinear_120to60_wholeNoteDuration),
        ("testSecondsOffsetLinear_60to120_dottedHalfDuration", testSecondsOffsetLinear_60to120_dottedHalfDuration),
        ("testSecondsOffsetLinear_60to120_wholeNoteDuration", testSecondsOffsetLinear_60to120_wholeNoteDuration),
        ("testSecondsOffsetLinear_60to60", testSecondsOffsetLinear_60to60),
        ("testSecondsOffsetPowerIn2_120to60", testSecondsOffsetPowerIn2_120to60),
        ("testSecondsOffsetPowerIn2_120to60_tooSmallResolution", testSecondsOffsetPowerIn2_120to60_tooSmallResolution),
        ("testSecondsOffsetPowerIn2_60to120", testSecondsOffsetPowerIn2_60to120),
        ("testSecondsOffsetPowerIn2_60to60", testSecondsOffsetPowerIn2_60to60),
        ("testTempoLinear_120to60", testTempoLinear_120to60),
        ("testTempoLinear_60to120", testTempoLinear_60to120),
        ("testTempoPowerIn2_120to60", testTempoPowerIn2_120to60),
        ("testTempoPowerIn2_60to120", testTempoPowerIn2_60to120),
        ("testTempoPowerIn3_120to60", testTempoPowerIn3_120to60),
        ("testTempoPowerIn3_60to120", testTempoPowerIn3_60to120),
    ]
}

extension TempoTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TempoTests = [
        ("testInitFloatLiteral", testInitFloatLiteral),
        ("testInitIntegerLiteral", testInitIntegerLiteral),
        ("testInterpolationStatic60BPMSecondsOffsets", testInterpolationStatic60BPMSecondsOffsets),
        ("testTempoRespellingSubdivision", testTempoRespellingSubdivision),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DurationTests.__allTests__DurationTests),
        testCase(DurationTreeTests.__allTests__DurationTreeTests),
        testCase(EasingEvaluateTests.__allTests__EasingEvaluateTests),
        testCase(EasingIntegrateTests.__allTests__EasingIntegrateTests),
        testCase(MeterCollectionTests.__allTests__MeterCollectionTests),
        testCase(MeterTests.__allTests__MeterTests),
        testCase(ProportionTreeTests.__allTests__ProportionTreeTests),
        testCase(RhythmTests.__allTests__RhythmTests),
        testCase(RhythmTreeTests.__allTests__RhythmTreeTests),
        testCase(TempoInterpolationCollectionTests.__allTests__TempoInterpolationCollectionTests),
        testCase(TempoInterpolationFragmentTests.__allTests__TempoInterpolationFragmentTests),
        testCase(TempoInterpolationTests.__allTests__TempoInterpolationTests),
        testCase(TempoTests.__allTests__TempoTests),
    ]
}
#endif
