theme: fullwidth
custom_categories:
  - name: "Basic Types"
    children:
      - "NoteNumber"
      - "Frequency"
      - "Pitch"
      - "Scale"
      - "Chord"
  - name: "Collections"
    children:
      - "Dyad"
      - "Collection"
  - name: "Intervals"
    children:
      - "OrderedInterval"
      - "UnorderedInterval"
  - name: "Interval Description"
      - "IntervalQuality"
      - "IntervalOrdinal"
      - "IntervalDescriptor"
      - "UnorderedIntervalDescriptor"
      - "OrderedIntervalDescriptor"
      - "CompoundIntervalDescriptor"
      - "ChordDescriptor"
  - name: "Tuning Systems"
    children:
      - "TuningSystem"
