#if !canImport(ObjectiveC)
import XCTest

extension IntervalSearchTreeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IntervalSearchTreeTests = [
        ("testInsertMaxUpdated", testInsertMaxUpdated),
        ("testIntervalContainsMultiple", testIntervalContainsMultiple),
        ("testIntervalContainsSingle", testIntervalContainsSingle),
        ("testIntervalNotContainedGreaterThan", testIntervalNotContainedGreaterThan),
        ("testIntervalNotContainedLessThan", testIntervalNotContainedLessThan),
        ("testManyIntervalsOverlapping", testManyIntervalsOverlapping),
        ("testPointContainsMultiple", testPointContainsMultiple),
    ]
}

extension MeterTempoTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MeterTempoTests = [
        ("testMeterBeatOffsets", testMeterBeatOffsets),
        ("testTempoDurationAt30", testTempoDurationAt30),
        ("testTempoDurationAt60", testTempoDurationAt60),
        ("testTempoDurationAt90", testTempoDurationAt90),
        ("testTempoDurationForBeatAtSubdivisionLevelDoubleAt60", testTempoDurationForBeatAtSubdivisionLevelDoubleAt60),
        ("testTempoDurationForBeatAtSubdivisionLevelHalfAt90", testTempoDurationForBeatAtSubdivisionLevelHalfAt90),
        ("testTempoDurationForBeatAtSubdivisionLevelSameAt60", testTempoDurationForBeatAtSubdivisionLevelSameAt60),
        ("testTempoInit", testTempoInit),
    ]
}

extension ModelTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ModelTests = [
        ("testAddMeter", testAddMeter),
        ("testAddTempo", testAddTempo),
        ("testFilterPerformanceContext", testFilterPerformanceContext),
        ("testHelloWorld", testHelloWorld),
        ("testInferOffset", testInferOffset),
        ("testManyRhythms", testManyRhythms),
        ("testSingleNoteRhythm", testSingleNoteRhythm),
        ("testSlur", testSlur),
    ]
}

extension PerformanceContextTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PerformanceContextTests = [
        ("testAddVoice", testAddVoice),
        ("testBuilder", testBuilder),
        ("testFilterInstruments", testFilterInstruments),
        ("testFilterPerformers", testFilterPerformers),
        ("testFilterPerformersAndVoices", testFilterPerformersAndVoices),
        ("testFilterVoices", testFilterVoices),
        ("testInitEmpty", testInitEmpty),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(IntervalSearchTreeTests.__allTests__IntervalSearchTreeTests),
        testCase(MeterTempoTests.__allTests__MeterTempoTests),
        testCase(ModelTests.__allTests__ModelTests),
        testCase(PerformanceContextTests.__allTests__PerformanceContextTests),
    ]
}
#endif
