theme: fullwidth
custom_categories:
  - name: Basic Types
    children: 
      - Beats
      - Subdivision
      - Duration
  - name: Meter
    children:
      - Meter
  - name: Tempo
    children:
      - Tempo
  - name: Rhythm
    children:
      - ProportionTree
      - DurationTree
      - Rhythm
      - AbsenceOrEvent
      - ContinuationOrInstance
      - event(_:)
      - rest()
      - tie()
      - />(_:_:)
      - "*(_:_)"
