#if !canImport(ObjectiveC)
import XCTest

extension ArticulationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ArticulationTests = [
        ("testArticulations", testArticulations),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ArticulationTests.__allTests__ArticulationTests),
    ]
}
#endif
