#if !canImport(ObjectiveC)
import XCTest

extension DynamicInterpolationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DynamicInterpolationTests = [
        ("testInitCrescendo", testInitCrescendo),
        ("testInitDescrescendo", testInitDescrescendo),
        ("testInitStatic", testInitStatic),
    ]
}

extension DynamicTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DynamicTests = [
        ("testAPI", testAPI),
        ("testNumericValues", testNumericValues),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DynamicInterpolationTests.__allTests__DynamicInterpolationTests),
        testCase(DynamicTests.__allTests__DynamicTests),
    ]
}
#endif
